name: Auto Increment Patch Tag

on:
  push:
    branches:
      - main  # Trigger only for the main branch

jobs:
  auto-patch-tag:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Step 2: Fetch tags from the repository
      - name: Fetch Tags
        run: git fetch --tags --quiet
      
      # Step 3: Get latest tag and increment PATCH
      - name: Calculate Next Patch Version
        id: set-version
        run: |
          # Get the latest tag (sorted by version)
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $latest_tag"
          
          if [ -z "$latest_tag" ]; then
            # No tags found, start with v1.0.0
            new_tag="v1.0.0"
          else
            # Extract version parts
            major=$(echo $latest_tag | cut -d '.' -f 1 | cut -c 2-)   # Remove 'v'
            minor=$(echo $latest_tag | cut -d '.' -f 2)
            patch=$(echo $latest_tag | cut -d '.' -f 3)
          
            # Increment PATCH
            new_patch=$((patch + 1))
            new_tag="v$major.$minor.$new_patch"
          fi
          
          echo "New Patch Tag: $new_tag"
          echo "::set-output name=tag::$new_tag"
      
      # Step 4: Push the new tag
      - name: Create and Push Tag
        env:
          NEW_TAG: ${{ steps.set-version.outputs.tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create the new tag
          git tag $NEW_TAG
          git push origin $NEW_TAG